module.exports = {
    USER_CONNECTED: 'USER_CONNECTED',
    USER_DISCONNECTED: 'USER_DISCONNECTED',
    START_GAME: 'START_GAME',
    GAME_STATE: 'GAME_STATE',
    INPUT_NUMBER: 'INPUT_NUMBER',
    TOGGLE_TIP: 'TOGGLE_TIP',
    JOIN_ROOM: 'JOIN_ROOM'
}